const strings = {
  PresetFlat: 'Preset: Flat',
  PresetFlatBed: 'Preset: Flat Bed',
  PresetZeroG: 'Preset: Zero G',
  PresetTV: 'Preset: TV',
  PresetUserFavorite: 'Preset: User Favorite',
  PresetMemory: 'Preset: Memory',
  PresetAntiSnore: 'Preset: Anti Snore',
  PresetMemory1: 'Preset: Memory 1',
  PresetMemory2: 'Preset: Memory 2',
  PresetMemory3: 'Preset: Memory 3',
  PresetMemory4: 'Preset: Memory 4',
  PresetRise: 'Preset: Rise',
  PresetDecline: 'Preset: Decline',
  PresetTiltForward: 'Preset: Tilt Forward',
  PresetTiltBackward: 'Preset: Tilt Backward',
  PresetAllFlat: 'Preset: All Flat',
  ProgramZeroG: 'Program: Zero G',
  ProgramTV: 'Program: TV',
  ProgramUserFavorite: 'Program: User Favorite',
  ProgramMemory: 'Program: Memory',
  ProgramAntiSnore: 'Program: Anti Snore',
  ProgramMemory1: 'Program: Memory 1',
  ProgramMemory2: 'Program: Memory 2',
  ProgramMemory3: 'Program: Memory 3',
  ProgramMemory4: 'Program: Memory 4',
  ResetMemory1: 'Reset: Memory 1',
  ResetMemory2: 'Reset: Memory 2',
  ResetTV: 'Reset: TV',
  ResetZeroG: 'Reset: Zero G',
  ResetAntiSnore: 'Reset: Anti Snore',
  MassageHeadStep: 'Head Massage Step',
  MassageFootStep: 'Foot Massage Step',
  MassageStep: 'Massage Step',
  MassageTimerStep: 'Massage Timer Step',
  MassageHeadStrength: 'Head Massage Strength',
  MassageFootStrength: 'Foot Massage Strength',
  AngleHead: 'Head Angle',
  AngleBack: 'Back Angle',
  AngleFoot: 'Foot Angle',
  AngleLeg: 'Leg Angle',
  SafetyLights: 'SafetyLights',
  SafetyLightsToggle: 'Toggle Safety Lights',
  UnderBedLightsToggle: 'Toggle Under Bed Lights',
  MassageToggle: 'Toggle Massage',
  MassageMode: 'Massage Mode',
};

export default strings;
