export type Device = {
  deviceID: number;
  sleeptrackerID: number;
  sleeptrackerProcessorID: number;
  name: string;
  type: number;
  active: boolean;
  macAddress: string;
  processorVersionHardware: string | null;
  processorVersionOS: string | null;
  processorVersionFirmware: string;
  unitNumber: number;
  lastDataSlotGMTSecs: number;
  lastHeartbeatGMTSecs: number;
  health: number;
  scannedSerialNumber: string;
  processorSerialNumber: string;
  processorCreateTimeGMTSecs: number;
  bedSize: number;
  brandID: number;
  packageID: any;
  modelID: string;
  mattressBrandID: number;
  mattressBrandName: string;
  mattressAgeYearPurchased: number;
  timeZone: string;
  lastWiFiRSSI: number;
  lastWiFiSignal: number;
  wifiSignalGood: boolean;
  baseSmartCableSupported: boolean;
  baseTandem: boolean;
  baseUnsynchronized: boolean;
  baseMotorsReversed: boolean;
  foundationSizeCode: number;
  mattressConfigurationCode: number;
  powerBaseSerialNumber: string;
  powerBase: {
    size: string;
    foundationSizeCode: number;
    supported: boolean;
    antiSnorePresetSupported: boolean;
    antiSnorePulseCount1: number;
    antiSnorePulseCount2: number;
    headAngleTicksPerDegree: number;
    footAngleTicksPerDegree: number;
  };
  enableDataPause: boolean;
};
